### ISSUE TITLE
Calculation not possible

### ISSUE THREAD

**Issue by miranyx** [aledog007/Calculator#2]
You can't calculate anything, it is being caused because of this line you are setting a function equal to a string thereby changing it from a function to a var.

https://github.com/aledog007/Calculator/blob/c9f49c7fa73f35ab2504beb1a3b615d77ec7639d/script.js#L9C14-L9C29

**Comment by aledog007** [comment]
okay, thanks

**Comment by miranyx** [comment]
Solved in [ac52e7f](https://github.com/aledog007/Calculator/commit/ac52e7f4b6e4ad054a342e7747d91d3d97cad73a)
